### ISSUE TITLE
访问Luxirty Search，页面不显示搜索框，无法正常使用

### ISSUE THREAD

**Issue by zhenzhuzhizhu** [bowencool/luxirty-search#1]
访问Luxirty Search，页面不显示搜索框，无法正常使用，请问是哪里的配置需要修改吗？
![2024-10-14_150101](https://github.com/user-attachments/assets/206f7078-7091-4842-93ee-bc9724af8bc3)

**Comment by bowencool** [comment]
抱歉我也是fork过来的，原仓库在这：https://github.com/KoriIku/luxirty-search

**Comment by zhenzhuzhizhu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，谢谢！
